# Generated by Django 5.0.7 on 2024-08-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, db_index=True, max_length=200, verbose_name='Адрес')),
                ('lat', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Широта')),
                ('lon', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Долгота')),
            ],
        ),
    ]
