# Generated by Django 5.0.7 on 2024-08-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interval', '0002_alter_geoplace_address_alter_geoplace_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoplace',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='geoplace',
            name='lon',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Долгота'),
        ),
    ]
