# Generated by Django 5.0.7 on 2024-07-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_alter_order_options_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'Детали заказа'},
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, db_index=True, max_length=200, verbose_name='Адрес'),
        ),
    ]
