# Generated by Django 5.0.7 on 2024-07-23 19:42

from django.db import migrations


def copy_prices_to_orderdetails(apps, schema_editor):
    OrderDetail = apps.get_model('foodcartapp', 'OrderDetail')

    for order in OrderDetail.objects.all().iterator():
        OrderDetail.objects.filter(id=order.id).update(amount=order.product.price)

class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_orderdetail_amount'),
    ]

    operations = [
        migrations.RunPython(copy_prices_to_orderdetails),
    ]
