# Generated by Django 5.0.7 on 2024-08-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_alter_order_options_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Принят'), ('2', 'Готовиться'), ('3', 'Доставляется'), ('4', 'Доставлен')], db_index=True, default='1', max_length=2),
        ),
    ]
